### ISSUE TITLE
Self-references under "Related" elements

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/website-sdgs#33] opened 2015-06-05 20:48 UTC
Each event and blog page (e.g., http://unstats.un.org/sdgs/first-iaeg-sdgs-meeting/ ) makes reference to itself

**Comment by mdotasia** [comment] 2015-06-05 21:17
Where?

**Comment by mdotasia** [comment] 2015-06-06 01:55
![screenshot](https://cloud.githubusercontent.com/assets/1482402/8017773/9b118478-0bcd-11e5-9d3a-931722642b55.gif)

**Comment by mdotasia** [comment] 2015-06-06 02:16
Can be reproduced for staging deployment via Travis CI (triggered by push to `staging`). Cannot be reproduced for the following local builds:

- `rake site:preview JEKYLL_ENV=staging`
- `rake site:preview TRAVIS_BRANCH=staging CI=true`

**Comment by mdotasia** [comment] 2015-06-06 22:40
This bug is the result of a workaround with [`html-proofer`](https://github.com/gjtorikian/html-proofer) in conjunction with `site.baseurl`. The lack of the `url_swap` option (https://github.com/gjtorikian/html-proofer/issues/219) makes it necessary to set `baseurl = ""` for validation. This makes it necessary to build the site twice: once with `baseurl` ignored for validation with `html-proofer` and then with `baseurl` honored to build the site to be published.

For production builds, the LSI is generated. This index is a class variable of [`RelatedPosts`](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/related_posts.rb). It is set in the [`build_index`](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/related_posts.rb#L28-L42), but only if it does not exist. This means that the LSI from the validation build survives and is still around for the second build.

For each post, related posts are determined from the LSI then the current post in excluded, see https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/related_posts.rb#L44-L46. This is done with this statement:

```
self.class.lsi.find_related(post.content, 11) - [post]
```

The subtraction operations uses hashes to determine whether posts are the same. the LSI in the second build is the one from the first build and so are the posts in the array. In the second run the hash values differ (for whatever reason), which means that the current posts is not excluded and recommendations will self-reference.

It's not really clear whether or not the LSI surviving between two runs is by design. Also it needs to be stated that if you run a build from the command line twice, this problem does not occur because subsequent builds are independent. But in this case the class is invoked in a rake task, which is called

**Comment by mdotasia** [comment] 2015-06-06 22:46
Will be fixed with https://github.com/UNStats/website-theme/issues/113.

**Closed** 2015-06-06 23:36 UTC
Labels: bug
